name: BattlePass
version: ${project.version}
main: com.battle.battlepass.battlepass.BattlePass
commands:
  bp:
    description: Comando do passe de batalha
  cq:
    description: Create Quest!
  startquest:
    description: Inicie uma quest
    permission: startquest.use